Added advection diffusion example
open-atmos/PyMPDATA pull request #427
Opened 2024-06-04 08:17 UTC by Kojec1

2024-06-04 08:55 UTC, slayoo commented
TODO:
- [ ] share simulation setting between Trixi.jl and PyMPDATA (e.g., through a common JSON file created in the notebook)
- [ ] save Julia simulation output to a file
- [ ] compare simulation output

2024-06-04 16:07 UTC, slayoo commented
@Kojec1 @pawelmagnu the matplotlib version issue is now fixed in the `main` branch, so I've just rebased this PR's branch accordingly

2024-07-01 22:30 UTC, slayoo commented
kudos @pawelmagnu for making it ✅

2024-09-05 15:47 UTC, slayoo requested changes

2024-09-05 15:47 UTC, slayoo commented on examples/setup.py
> +        "h5py",
it seems h5py is finally not used in this PR, right?

2024-09-05 15:47 UTC, slayoo commented on .github/workflows/tests+pypi.yml
> +      - run: julia -e 'using Pkg; Pkg.add("Trixi")'
it seems, Trixi is not used in this PR anymore, right?

2024-09-05 15:47 UTC, slayoo commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
there is an error in the notebook committed:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[54], line 3
      1 plt.imshow(solver.advectee.get().copy(), cmap='viridis')
      2 plt.colorbar()
----> 3 show_plot()

NameError: name 'show_plot' is not defined
```

2024-09-05 15:47 UTC, slayoo commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
despite importing `sympy` and defining an analytic solution, it is not used in this example. If not comparing to analytical solution, it would be great to at least include a smoke test with this PR so that in case things will be broken by some other developments, we will get notified of such regression.

2024-09-05 15:47 UTC, slayoo commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
let's remove the commented-out code before merging:
```
        # [
            init_conditions(x, y) for x in np.linspace(min_x, max_x, nx)
        # ]
```

2024-09-05 15:47 UTC, slayoo commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
it would be user-friendly to label the plot axes (x, y, colorbar)

2024-09-05 22:20 UTC, pawelmagnu commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
resolved in the last commit

2024-09-05 22:20 UTC, pawelmagnu commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
resolved in the last commit

2024-09-06 08:40 UTC, slayoo commented on examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb
One more issue:
```
plt.show()
show_plot()
```
the idea of `show_plot` is to be a drop-in replacement for `pyplot.show()` in order to switch to svg plots within notebooks and to offer save-as-pdf/svg buttons. Here, `plt.show()` already displays the figure as png, and `show_plot()` thus does nothing. `show_plot()` to be removed.

2024-09-06 19:04 UTC, pawelmagnu commented
@slayoo examples on windows still time out after 3 re-run, could you help with that?

2024-09-06 21:12 UTC, slayoo commented
> @slayoo examples on windows still time out after 3 re-run, could you help with that?

let's see if these will help: #452, #451

2024-09-06 22:31 UTC, slayoo commented
closing & reopening to see if build against current main (with #452 merged) works

2024-09-07 07:58 UTC, slayoo approved these changes

2024-09-07 07:58 UTC, merged