comparison against trixi via 2d advection
open-atmos/PyMPDATA pull request #454
Opened 2024-09-08 16:45 UTC by pawelmagnu

2024-09-11 09:25 UTC, slayoo requested changes

2024-09-11 09:25 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
why do we need `assert SETUP["nx"] == SETUP["ny"]`?

2024-09-11 09:25 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
we definitely need some introductory narrative in the header explaining:
- what is Trixi
- what is the problem solved and what is the aim of the comparison
- what kind of numerical method and mesh Trixi uses
- what is the approach technically: common JSON file, interpolation using Trixi2VTK, etc
- what and how needs to be installed (e.g., on Colab) to run the notebook

2024-09-11 09:25 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
the `def z(t)` function is a copy-paste from the 2D advection-diffusion example, better make reusable there and import here

2024-09-11 09:25 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
`omega` (and `mu`, and coordinates min/max) should be part of the shared json

2024-09-11 09:25 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
the plot is not visible on GitHub in the notebook

2024-09-11 09:30 UTC, pawelmagnu commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
the way converting vtu to numpy array works only supports square matrices

2024-09-11 09:36 UTC, slayoo commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
let's then comment it with a GitHub issue URL!

2024-09-11 10:57 UTC, pawelmagnu commented on examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb
i'll try to fix my code to support rectangular size

2024-10-14 12:26 UTC, slayoo commented
@pawelmagnu, it seems that the green "passes" of the notebook execution on Windows and macOS are actually silent failures. Adding some print statements results in no output. On macOS, the following is caught on stderr:
```
_ test_run_notebooks[examples/PyMPDATA_examples/advection_diffusion_2d/advection-diffusion-2d.ipynb] _
----------------------------- Captured stderr call -----------------------------
Assertion failed: false (src/object.cpp:438)
```
It would be best to replace in the notebook the "!" shell magics with Python subprocess execution including exit status checks to know if actually anything was executed and what was the status code.

2024-11-01 23:14 UTC, slayoo commented
@pawelmagnu, trying the notebook on Colab (https://colab.research.google.com/github/pawelmagnu/PyMPDATA/blob/trixi_comparison/examples/PyMPDATA_examples/trixi_comparison/advection_comparison.ipynb), it fails due to missing Julia binary:
![image](https://github.com/user-attachments/assets/89e89393-caff-476b-9e53-ff0eae8b4872)

Analogous error will likely happen on mybinder.

Let's try to add a notebook cell with Julia installation magick

2024-11-07 22:05 UTC, slayoo commented
@pawelmagnu it works on Colab now!
![image](https://github.com/user-attachments/assets/38210bed-f78c-40b4-b07d-506e9f0cac85)
Kudos!

2024-11-07 22:06 UTC, slayoo approved these changes, later dismissed

2024-11-08 17:34 UTC, slayoo approved these changes

2024-11-08 17:35 UTC, merged